favicon: /favicon.ico


# Nav Menus
menu:
    Index: /
    Archives: /archives

# Nav Shortcut Icons
nav_icons:
    - ['/images/github.svg', 'https://github.com/blackpost38']
    - ['/images/rss.svg', '/atom.xml']

# # Friend Links
# friend_links:
#     - ['AngryPowman', 'This is a link', 'http://powman.org']
#     - ['Demo Links', 'You can change this in your theme config', 'http://powman.org']


# About
about_info:
    name: "Hyunju Choi"
    bio: "Web Developer"
    avatar: "/images/avatar.png"

# Comment
# e.g disqus: seansun
disqus: blackpost38
duoshuo: 

# Analytics
google_analytics: UA-69991496-1
tencent_analytics: 
 
# Copyright Infomation
startyear: 2018
